sudo: false
language: java
jdk:
- oraclejdk9
branches: 
cache:
  directories:
  - "$HOME/.cache"
maven:
  version: 3.5.2
env:
  global:
  - MAVEN_HOME: "/usr/local/maven-3.5.2"
after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage
  reports"